trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - product-app/prisma
    exclude:
      - README.md
      - CHANGELOG.md
      - Makefile

resources:
  repositories:
    - repository: default
      type: git
      name: devops-setup

variables:
  - group: common-vars
    
pool:
  vmImage: $(POOL_IMAGE)

stages:
  - stage: prod
    condition: eq( variables['Build.SourceBranchName'], 'master' )
    displayName: Prod
    jobs:       
        -   job: 
            displayName: Migrate Database     
            steps:
            -   task: NodeTool@0
                inputs:
                    versionSpec: $(NODE_BUILD_VERSION)
                displayName: Install Node.js
            -   script: npm install -g prisma
            -   task: SystemsManagerGetParameter@1
                inputs:
                    awsCredentials: 'AWS_prod_CONNECTION'
                    regionName: $(PROD_AWS_REGION)
                    readMode: 'hierarchy'
                    parameterPath: '/prod/swiftserve/postgres'
                    recursive: true
            -   script: prisma migrate deploy
                env:
                    DATABASE_URL: $(/PROD/SWIFTSERVE/POSTGRES/PRODUCT-DB)
                workingDirectory: product-app
  - stage: dev
    condition: ne( variables['Build.SourceBranchName'], 'master' )
    displayName: Dev
    jobs:
        -   job: 
            displayName: Migrate Database     
            steps:
            -   task: NodeTool@0
                inputs:
                    versionSpec: $(NODE_BUILD_VERSION)
                displayName: Install Node.js
            
            -   script: npm install -g prisma
            -   task: SystemsManagerGetParameter@1
                inputs:
                    awsCredentials: 'AWS_dev_CONNECTION'
                    regionName: $(DEV_AWS_REGION)
                    readMode: 'hierarchy'
                    parameterPath: '/dev/swiftserve/postgres'
                    recursive: true
            -   script: prisma migrate deploy
                env:
                    DATABASE_URL: $(/DEV/SWIFTSERVE/POSTGRES/PRODUCT-DB)
                workingDirectory: product-app