trigger:
  branches:
    include:
      - "master"
      - "develop"
  paths:
    include:
      - customer-web-backend
    exclude:
      - README.md
      - CHANGELOG.md
      - Makefile
      - customer-web-backend/azure-pipelines-db.yml
      - customer-web-backend/azure-pipelines.yml

resources:
  repositories:
    - repository: default
      type: git
      name: devops-setup

variables:
  - group: common-vars
    
pool:
  vmImage: $(POOL_IMAGE)

stages:
  - stage: prod
    displayName: Production
    condition: eq( variables['Build.SourceBranchName'], 'master' )
    jobs:
      - job: prod_build
        displayName: Prod Build
        steps:
        - template: templates/step-ng-ecr-ci.yml@default
          parameters:
            path: customer-web-backend
            serviceName: customer-web-backend
            dockerFile: customer-web-backend/Dockerfile
      # - job: prod_deploy_pr
      #   displayName: Prod PR for Deploy
      #   dependsOn: prod_build
      #   continueOnError: false
      #   variables:
      #     IMAGE_VERSION: $[ dependencies.prod_build.outputs['setImageVersion.IMAGE_VERSION'] ]
      #   steps:
      #   - template: templates/step-auto-pl-ci.yml@default
      #     parameters:
      #       repoName: infrastructure
      #       filePath: /prod/customer-web-backend/IMAGE
      #       fileContent: $(IMAGE_VERSION)
      
  - stage: dev    
    displayName: Development
    condition: eq( variables['Build.SourceBranchName'], 'develop' )
    jobs:
      - job: dev_build
        displayName: Dev Build
        steps:
        - template: templates/step-ng-ecr-ci.yml@default
          parameters:
            path: customer-web-backend
            serviceName: customer-web-backend
            dockerFile: customer-web-backend/Dockerfile
      # - job: dev_deploy_pr
      #   displayName: Dev PR for Deploy
      #   dependsOn: dev_build
      #   continueOnError: false
      #   variables:
      #     IMAGE_VERSION: $[ dependencies.dev_build.outputs['setImageVersion.IMAGE_VERSION'] ]
      #   steps:
      #   - template: templates/step-auto-pl-ci.yml@default
      #     parameters:
      #       repoName: infrastructure
      #       filePath: /dev/customer-web-backend/IMAGE
      #       fileContent: $(IMAGE_VERSION)